// Generated by docs/submission/capture_raw.py — do not hand-edit.
export const RAW_DURATION_SEC = 124.280;
export const TIMELINE: { t: number; label: string }[] = [
  {
    "t": 3.71,
    "label": "Operator wall. Video stays on departmental NVRs \u2014 this is the hit picture."
  },
  {
    "t": 10.57,
    "label": "Gov feeds \u2014 official Sentinel cameras, proxied live through GUSIP"
  },
  {
    "t": 13.11,
    "label": "Chimanbhai Bridge \u2014 jury-provided Sentinel camera, live through the GUSIP proxy."
  },
  {
    "t": 36.27,
    "label": "Own/demo wall \u2014 RTSP / ONVIF / vendor cameras. Watchlist: stolen Fortuner GJ 01 ST 0001."
  },
  {
    "t": 39.29,
    "label": "Corridor firing: Paldi / SG Highway / Thaltej / Gandhinagar. Target: inbox under 8 seconds."
  },
  {
    "t": 39.8,
    "label": "Hit landed \u2014 GJ 01 ST 0001 flagged on the wall."
  },
  {
    "t": 55.84,
    "label": "Investigate \u2014 purpose is mandatory and audited. Operators cannot export CSV."
  },
  {
    "t": 69.12,
    "label": "GIS polyline: five hops, two cities. One line instead of three phone calls."
  },
  {
    "t": 75.87,
    "label": "Statewide GIS \u2014 cameras, coverage, yellow pins for open alerts."
  },
  {
    "t": 83.38,
    "label": "Coordinator (Ahmedabad) \u2014 home district only, until break-glass."
  },
  {
    "t": 88.52,
    "label": "Ahmedabad coordinator. Cameras outside home district are hidden."
  },
  {
    "t": 103.14,
    "label": "Break-glass: FIR reason is audited. Access expires on a timer even if they forget to End."
  },
  {
    "t": 109.64,
    "label": "Statewide cameras unlocked for 30 minutes. End now returns the coordinator to Ahmedabad."
  }
];
